language: ruby
cache: bundler
bundler_args: --without tools
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
sudo: required
